### ISSUE TITLE
Web Keepers' Technology Idea Submission

### ISSUE THREAD

**Issue by CuriousLearner** [mozilla/TBTWBuildChallenge#27]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Web Keepers
- Challenge Contact Person Name: Sanyam Khurana
- Campus Name: Northern India Engineering College
### Idea Description

_Please answer all of the questions below._
- Idea name: MozWebProtect
- What is the problem you are solving for:

The aim of the project is to develop a browser extension that can help the users report the spamming mailing lists when a mail appears in the browser. The reported data will be stored in an online database and will be used to generate warnings when the user with the extension installed visits a site that is spamming on its mailing list.
The extension will help the users reduce the number of spam e-mails they receive by warning them in advance about a spam site before they enter there e-mail and subscribe to the website. On a larger scale the database of reported links will be made publicly accessible to the developers free of cost through an API which allows other developers to use the database to create better tools and softwares.

Aims of the project

```
- To create a browser extension to warn users about spamming websites
- To create a online database of spam websites
- To provide a public API to access the reported data for building better tools
```
- Who encounters that problem (who is your audience - describe them):

Everyone now-a-days subscribe to multiple sites and most of these sites don't stop sending mails even after un-subscribing their service. Some sites spam the mailbox with lot of unwanted mails. All these people are our targeted audience.
- How will your tool solve this problem for these people:  

This tool would allow people to know in advance if the spam score of a site is high and thus warns user before even subscribing to it. Also, the API along with the online database would be made available to other developers to create better tools and services.
- What are you going to create (app, add-on, extension, etc.): 

_Browser Extension_

The browser extension forms the frontend to our project and will be installed by the user on the browsers supported by the plugin. The plugin will be used to establish the communication with the server through the REST APIs exposed by the server.
The plugin will provide the feature of reporting the spam links to the server by the user. To report a link all the user has to do is to right click on the spam link and click on report link.
Whenever the user click the report link, the link is submitted to the server where automated verification of the link takes place before storing into the database.
The browser extension using the data provided by the Server will generate a graphical non-
intrusive warning whenever a user visits a site that has been reported for a lot of spam mails.

_REST API_

The project server forms the backend for the project and provides background functionality to the browser extension by exposing REST APIs which provides the functionality to store the reported links.

The work of the server is to verify a link when it is reported by the user. The verification of the link can take place through various algorithms like checking the number of instance the link has been reported or validating the list against the white-listed domains. Only the links that pass the validation will be stored in the database.
To maintain the privacy of the user, the server won’t store the logs of the websites visited by the user and the anonymously reported data won’t be used for any commercial or spam activity.
- What are the next steps for building this tool:
  - Decide DB Schema
  - Decide API calls
  - Freeze Interface requirements
  - Start working on API and extension in parallel

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by mikeconley** [comment]
Hey Web Keepers,

Thanks for your submission. According to [the Take Back the Web Build Challenge website](https://takebacktheweb.mozilla.community/role/build-technology/), the goal is to: "design a prototype of a powerful tool that will help people understand why privacy and security is important. It can be an app, an add-on, extension, plugin, website or anything that helps people be more aware of their privacy & security online."

I agree that spam is a problem, and an important one to try to solve, but can you expand on how this will help people understand why privacy and security is important?

I have some other questions regarding this project:
- How do you prevent abuse? As in, people submitting URLs for some site that they want to have a low rating, despite that site not sending out spam?
- The links from spam often don't link back to the site that caused me to receive the spam (for example, I get spam about cheap pharmaceuticals, but I've certainly never been to a cheap pharmaceutical website).
- How do you allow users to get information about the spammy websites they might be visiting without having them send what sites they're visiting as they go? I don't know if saying "we won't save logs" is a good enough mechanism. Especially for a campaign about security and privacy.

So, to reiterate, is there a way you can reframe this project so that it aligns more with the security and privacy theme of this Take Back the Web Challenge?

**Comment by h4xr** [comment]
Hello,
I am Saurabh from The WebKeepers team, I would like to add some clarifications on the questions raised:

1). The tool uses a threshold value to decide whether a particular website is known for sending spam or not. For example, If a user submits a website to the database for spam, the service will not generate any warning until 'X' number of users have reported the link is reported as spam.
Also, the service provides an easy to fill form for the website owners which can be used to submit a request for removal of the website from the spam database.

2). The aim of the extension is not to clear the spam from the users inbox but is rather to make the user aware where to submit their E-Mail addresses. 

3). For the extension to work, we need to listen to which site the user has opened in the browser tab. The URL of the site is sent to the server where it is checked against the spam database. 
An alternative approach is to make the extension update its offline site database periodically either via a scheduled mechanism or via periodic extension updates which can then be used to generate warning by the extension.

**Comment by mikeconley** [comment]
Hey Saurabh,

Thanks for getting back to me.

> 1). The tool uses a threshold value to decide whether a particular website is known for sending spam > or not. For example, If a user submits a website to the database for spam, the service will not 
> generate any warning until 'X' number of users have reported the link is reported as spam.
> Also, the service provides an easy to fill form for the website owners which can be used to submit a
> request for removal of the website from the spam database.

Okay, I understand. I should point out that this is still open to abuse - a reasonably well connected brigade of bad actors (_cough_ 4chan _cough_) could, with little difficulty, coordinate to add a warning to some site just by having lots of different people submit it.

Just something to think about.

> 2). The aim of the extension is not to clear the spam from the users inbox but is rather to make the 
> user aware where to submit their E-Mail addresses. 

I think this part still needs fleshing out. From my understanding, you want to crowd-source spam information, extract the links that that spam links to, and use that to add warnings to sites. On the surface that sounds reasonable, but my 2nd bullet remains. I'll rephrase.

Suppose I fill out some form on Site A, giving them my email address. Site A, without my consent, sells my email address to Evil Corp. Evil Corp then starts sending me spam regarding some Site C.

My email inbox is now filled with spam for Site C. How do you correlate that to Site A so that future users know not to give Site A their contact information?

**Comment by charissalaisy** [comment]
@CuriousLearner, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @CuriousLearner! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by h4xr** [comment]
@mikeconley I understand your point, we can't point out to the sites which sells the user details to other mailers. For that, I think what we can do is, whenever a page is loaded or reloaded, we can check the page if it contains some link or email address which has been reported as spam and generate a warning based on that.

For the time, we are working on the prototype of the browser extension, will be updating soon with the progress.

**Comment by bacharakis** [comment]
Hi @h4xr , looking forward seeing your prototype :D
