### ISSUE TITLE
Password Lock firefox browser

### ISSUE THREAD

**Issue by SiddheshDixit** [mozilla/TBTWBuildChallenge#29]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: MozPallotti
- Challenge Contact Person Name: Siddhesh Dixit
- Campus Name: St.Vincent Pallotti College of Engineering & Technology,Nagpur
### Idea Description

_Please answer all of the questions below._
- Idea name:Password lock firefox browser
- What is the problem you are solving for: I want to solve one problem that if we password lock mozilla firefox(Desktop browser) with the help of username and password no one can access our browser at all.So it wil help user to secure their passwords no need to logout their support mozilla,facebook account everytime.
- Who encounters that problem (who is your audience - describe them): problem encounter by me and my classmates.
- How will your tool solve this problem for these people:  if user enter wrong password then browser will not open and vice versa.
- What are you going to create (app, add-on, extension, etc.): 
  add-on
- What are the next steps for building this tool: 
  to analyze the users need.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by mikeconley** [comment]
Hey MozPallotti,

You have an interesting idea. Firefox stores data in user profile directories (if you go to about:profiles in a Nightly build, you can find the list and a button to directly open the profile data folder in your OS).

I think I want to know more about what kind of data you want to secure. If you want to, for example, encrypt and secure the _entire_ profile directory, then your idea of using an add-on is probably not going to work because the profile directory typically stores the add-on code that a user has installed (so once the directory is encrypted, the tool to decrypt will also be encrypted).

So you'll probably want to encrypt / secure specific things within that profile directory. Can you go into more detail about what you'd like to secure?
- Passwords
- History
- Cookies

anything else?

**Comment by charissalaisy** [comment]
@SiddheshDixit, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @SiddheshDixit! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
