### ISSUE TITLE
CrypticOperation

### ISSUE THREAD

**Issue by irvifa** [mozilla/TBTWBuildChallenge#41]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: cryptopt
- Challenge Contact Person Name: Irvi Firqotul Aini
- Campus Name: University of Indonesia
### Idea Description

_Please answer all of the questions below._
- Idea name: CrypticOperation
- What is the problem you are solving for: Awareness of privacy in public wireless infrastructure and public services
- Who encounters that problem (who is your audience - describe them): student community in my university
- How will your tool solve this problem for these people: It will warn the people in my community about the importance of privacy in public infrastructures and services, such as usage of wireless sharing in public wireless infrastructure such as warning if there is a suspicious 
- What are you going to create (app, add-on, extension, etc.): app, add-ons, extension
- What are the next steps for building this tool: create a prototype and do a scavenger hunt more about this idea
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @mikeconley @wagnerand

**Comment by mikeconley** [comment]
Hey cryptopt,

I have some feedback for you!

> such as usage of wireless sharing in public wireless infrastructure such as warning if there is a 
> suspicious 

You're going to need to finish that sentence. This is a pretty important part of the pitch, so being really clear about how you envision your tool solving the problem is really important. I assume you'd be warning about suspicious network activity? What kind of suspicious network activity?

I'm also curious to know how you will define "public wireless infrastructure"? Is this the wireless infrastructure of your University network? How will you detect when the user is on such an infrastructure?

I'm also interested in knowing more about the scavenger hunt you mention in your second-to-last bullet point.

**Comment by charissalaisy** [comment]
@rvu95, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @rvu95! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
