### ISSUE TITLE
Sistema de Gerenciamento de Cookies

### ISSUE THREAD

**Issue by ndl-securityteam** [mozilla/TBTWBuildChallenge#75]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: NDL - Security Team
- Challenge Contact Person Name: Núcleo de Desenvolvimento Livre
- Campus Name: Instituto Federal de Educação, Ciência e Tecnologia Campus Votuporanga
### Idea Description

_Please answer all of the questions below._
- Idea name: Sistema de Gerenciamento de Cookies.
- What is the problem you are solving for: O acumulo e a falta de segurança no que diz respeito aos cookies.
- Who encounters that problem (who is your audience - describe them):  Com a utilização de cookies algumas informações, como login e senha podem ser salvas a fim de não serem necessárias na próxima visita ao site, isso facilita a navegação mas apresentam riscos quando o computador é compartilhado com outras pessoas. Também podem representar riscos à privacidade do usuário, já que sites também ficam registrados em arquivos como estes. Cookies, em sua maioria, são arquivos pequenos, mas que podem se acumular cada vez mais aumentando o espaço utilizado e, em algumas vezes, atrapalhando o desempenho da máquina.
- How will your tool solve this problem for these people: Um sistema web com gerenciamento de cookies utilizando HTML, PHP, CSS, Bootstrap e JavaScript. 
- What are you going to create (app, add-on, extension, etc.): Sistema web
- What are the next steps for building this tool: Programar a interface visual do sistema e formatar as informações que aparecerão para o usuário. 
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @brianking and @bacharakis

**Comment by cpswsg** [comment]
_Translating to English_
- Idea name: Cookies Management System
- What is the problem you are solving for: Cookies accumulation and the lack of security.
- What is the problem you are solving for: Who encounters that problem (who is your audience - describe them): Through the use of cookies some information such as logins and passwords, can be saved so that they aren't required at the next visit to the site. This facilitates the web navigation, but represents a risk when the computer is shared with others people. Also, cookies are, mostly, small files but can accumulate increasingly the space use and reduce perfomance of the machine.
- How will your tool solve this problem for these people: Web system with cookie management using HTML, PHP, CSS, Bootstrap and JavaScript.
- What are you going to create (app, add-on, extension, etc.): Web System
- What are the next steps for building this tool: Program the visual interface of the system and format the informations that will appear to the users.

**Comment by brianking** [comment]
Hi @ndl-securityteam @cynthiapereira 

Can you elaborate a bit more on this please. I don't have enough information to review. In particular, what exactly will the tool look like and what will it do? How is it different from cookie managers built into browsers?

**Comment by LucyeoH-zz** [comment]
@ndl-securityteam @cynthiapereira  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @ndl-securityteam @cynthiapereira!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful tools for taking your idea to the next level.
